### ISSUE TITLE
make rooms case insensitive

### ISSUE THREAD

**Issue by cyphar** [kennib/necsus#76] opened 2021-01-11 12:51 UTC

**Comment by joelgibson** [comment] 2023-01-14 00:44
I didn't think this was an issue this year.

**Comment by sheabunge** [comment] 2023-01-14 03:00
Students seemed pretty fine using exact casing for rooms. I'd be potentially concerned that changing this might cause additional confusion.

**Comment by joelgibson** [comment] 2023-12-31 03:53
Closing this and making a note in the README that this is by design.

**Closed as completed by joelgibson** 2023-12-31 03:53 UTC
